# Generated by Django 5.2.5 on 2025-09-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('image_example', models.ImageField(blank=True, null=True, upload_to='disease_examples/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.ImageField(upload_to='upload/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='model_files/')),
                ('version', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('confidence', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='banana_api.disease')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='banana_api.imageupload')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.TextField()),
                ('source', models.URLField(blank=True, max_length=500, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='banana_api.disease')),
            ],
        ),
    ]
